version: '2.0'

services:

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ThePassword
      MYSQL_DATABASE: qmoney
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword